# flags:
CC = g++ -std=c++17 -Wall -pedantic


# paths:
PATH_SRC := src
PATH_INC := include
PATH_BUILD := build
#PATH_BIN := $(PATH_BUILD)/bin
PATH_OBJ := $(PATH_BUILD)/obj


OUT = ClubsAgeStats.out

#---------------------------------------------------------
$(OUT): $(PATH_SRC)/ClubsAgeStats.cpp $(PATH_INC)/const.hpp
	$(CC) $(PATH_SRC)/ClubsAgeStats.cpp -o $(OUT)
	

#---------------------------------------------------------
